#!/usr/bin/env bash
# ==============================================================================
# SignalX: AI Agent Documentation Compiler
# Compiles modular docs from docs/.ai/ into AGENTS.md, GEMINI.md, and CLAUDE.md
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

DOCS_AI_DIR="${ROOT_DIR}/docs/.ai"
OUTPUT_AGENTS="${ROOT_DIR}/AGENTS.md"
OUTPUT_GEMINI="${ROOT_DIR}/GEMINI.md"
OUTPUT_CLAUDE="${ROOT_DIR}/CLAUDE.md"

TEMP_FILE=$(mktemp)

cat << 'EOF' > "${TEMP_FILE}"
# SignalX Master AI Agent Documentation

> **Auto-Generated File**: Do not edit this file directly. Edit the source documents in `docs/.ai/` and re-run `bash scripts/generate_agents_markdown.sh`.

`signalx` is a production-grade Python library for extracting 100+ standardized trading signals (`"buy"`, `"sell"`, `"hold"`, `"none"`) from any OHLCV dataset.

---

EOF

# Concatenate all docs in logical sequence
FILES=(
    "${DOCS_AI_DIR}/AI_AGENT_GUIDELINE.md"
    "${DOCS_AI_DIR}/RULE.md"
    "${DOCS_AI_DIR}/STRUCTURE.md"
    "${DOCS_AI_DIR}/GIT_CONVENTIONS.md"
    "${DOCS_AI_DIR}/CONFIGURATION.md"
    "${DOCS_AI_DIR}/USAGE.md"
    "${DOCS_AI_DIR}/SIGNALS_CATALOG.md"
)

for file in "${FILES[@]}"; do
    if [ -f "${file}" ]; then
        echo "Appending $(basename "${file}")..."
        echo "" >> "${TEMP_FILE}"
        echo "---" >> "${TEMP_FILE}"
        echo "" >> "${TEMP_FILE}"
        cat "${file}" >> "${TEMP_FILE}"
    else
        echo "Warning: ${file} does not exist." >&2
    fi
done

# Copy compiled file to all target agent docs
cp "${TEMP_FILE}" "${OUTPUT_AGENTS}"
cp "${TEMP_FILE}" "${OUTPUT_GEMINI}"
cp "${TEMP_FILE}" "${OUTPUT_CLAUDE}"
rm -f "${TEMP_FILE}"

echo "Successfully generated:"
echo "  - ${OUTPUT_AGENTS}"
echo "  - ${OUTPUT_GEMINI}"
echo "  - ${OUTPUT_CLAUDE}"
